[package]
name = "bevy_state_curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
interp = "1.0.2"
interpolation = "0.3.0"
lerp = "0.5.0"
